### ISSUE TITLE
Compilation on macOS

### ISSUE THREAD

**Issue by peterjc** [markmoraes/jove#3]
How should jove be compiled on macOS?

There are clear references to macOS (and Mac OS X) in the code, but I suspect ``README.mac`` is for the legacy Mac operating system not based on Unix.

**Comment by peterjc** [comment]
Just running "make" fails on macOS as follows:

```
$ make
...
x86_64-apple-darwin13.4.0-clang -O  -DLinux -D_FORTIFY_SOURCE=2 -isystem /Users/pc40583/miniconda3/include  -c -o io.o io.c
io.c:982:15: warning: implicit declaration of function 'readlink' is invalid in C99 [-Wimplicit-function-declaration]
                                linklen = readlink(intobuf, linkbuf, sizeof(linkbuf)-1);
                                          ^
1 warning generated.
if ! cmp -s paths.h paths.tmp 2> /dev/null; then mv paths.tmp paths.h; else rm paths.tmp; fi
x86_64-apple-darwin13.4.0-clang -O  -DLinux -D_FORTIFY_SOURCE=2 -isystem /Users/pc40583/miniconda3/include  -c -o jove.o jove.c
jove.c:1829:23: error: use of undeclared identifier 'SIGWINCH'
        (void) setsighandler(SIGWINCH, win_reshape);
                             ^
1 error generated.
make: *** [jove.o] Error 1
```

Am I meant to edit the ``Makefile`` to replace ``SYSDEFS = -DLinux`` with ``SYSDEFS = -DDarwin`` which seems to work?

**Comment by markmoraes** [comment]
Yes, README.mac is for archaic pre-Darwin/OSX (and has not been built in forever).   It should probably be removed.

The remaining README need a cleanup, I'll do that shortly, but yes, you're right,
make SYSDEFS=-DDarwin 
should work for modern MacOS X onwards.

**Comment by peterjc** [comment]
Thanks for confirming I was on the right track for macOS 👍

**Comment by markmoraes** [comment]
Docs should be better in 4_17 branch, the new buildflags.sh script should work on Darwin.

**Comment by peterjc** [comment]
Just to note, this worked fine on 4.17.3.6 for conda-forge:

```
make JOVEHOME="$PREFIX" SYSDEFS=-DDarwin install
```

I may look into ``buildflags.sh`` at some point.
