### ISSUE TITLE
Jove doesn't build on Hurd

### ISSUE THREAD

**Issue by C0RD** [markmoraes/jove#10]
Hi,

Jove doesn't build on Hurd.[

Logfiles at https://buildd.debian.org/status/fetch.php?pkg=jove&arch=hurd-i386&ver=4.17.4.1-1&stamp=1653931103&raw=0 

It fails with

```
cc -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 `./buildflags.sh --cflags` -Wdate-time -D_FORTIFY_SOURCE=2  -c -o re.o re.c
cc -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 `./buildflags.sh --cflags` -Wdate-time -D_FORTIFY_SOURCE=2  -c -o screen.o screen.c
cc -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 `./buildflags.sh --cflags` -Wdate-time -D_FORTIFY_SOURCE=2  -c -o termcap.o termcap.c
cc -g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 `./buildflags.sh --cflags` -Wdate-time -D_FORTIFY_SOURCE=2  -c -o unix.o unix.c
In file included from unix.c:20:
ttystate.h:25:12: fatal error: termio.h: No such file or directory
   25 | #  include <termio.h>
      |            ^~~~~~~~~~
compilation terminated.
make[2]: *** [<builtin>: unix.o] Error 1
make[2]: Leaving directory '/<<PKGBUILDDIR>>'
dh_auto_build: error: make -j1 "INSTALL=install --strip-program=true" "OPTFLAGS=-g -O2 -ffile-prefix-map=/<<PKGBUILDDIR>>=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2" "LDFLAGS=-Wl,-z,relro -Wl,-z,now" JOVEHOME=/usr JMANDIR=/usr/share/man/man1 LOCALCC=i686-gnu-gcc returned exit code 2
make[1]: *** [debian/rules:19: override_dh_auto_build] Error 255
make[1]: Leaving directory '/<<PKGBUILDDIR>>'
make: *** [debian/rules:14: binary-arch] Error 2
```

I'm currently trying to get my hands on a Hurd-Box. I had it working on Hurd some years back, but that was lost somehow.

**Comment by markmoraes** [comment]
Try 4.17.4.3 -- I added a "GNU" case in buildflags.sh and sysdep.h that's the same as Linux and it seems to build in a kvm of 0.9 (I followed https://www.debian.org/ports/hurd/hurd-install )

```
wget https://cdimage.debian.org/cdimage/ports/stable/hurd-i386/debian-hurd.img.tar.gz
tar xzf debian-hurd.img.tar.gz
kvm -m 1G -drive file=$(echo debian-hurd*.img),cache=writeback
```

Then used `wget https://github.com/jonmacs/jove/archive/refs/tags/4.17.4.3.tar.gz` to grab the Jove tarball and was able to run `testbuild.sh` (I forgot to fix testbuild.sh in 4.17.4.2)

**Comment by C0RD** [comment]
thanks  @markmoraes . works like a charm.

https://buildd.debian.org/status/fetch.php?pkg=jove&arch=hurd-i386&ver=4.17.4.3-1&stamp=1654892027&raw=0
